#!/bin/bash
# Sync latest code from GitHub to Replit.
# Run from the project root in the Replit shell:
#   bash scripts/sync-from-github.sh
#
# Replit-only files are NEVER touched:
#   lib/staff-data.ts, lib/settings.ts, replit.md, data/*.json

REPO="llamanftstaking-glitch/MC-Hair-Salon"
BRANCH="main"
BASE="https://raw.githubusercontent.com/${REPO}/${BRANCH}"

REPLIT_ONLY=(
  "lib/staff-data.ts"
  "lib/settings.ts"
  "replit.md"
  "data/customers.json"
  "data/gift-cards.json"
  "data/messages.json"
  "data/staff.json"
)

# Files to download from GitHub (everything tracked except Replit-only)
FILES=(
  "package.json"
  "tsconfig.json"
  "next.config.ts"
  "postcss.config.mjs"
  "eslint.config.mjs"
  "components.json"
  "middleware.ts"
  "app/layout.tsx"
  "app/page.tsx"
  "app/globals.css"
  "app/manifest.ts"
  "app/robots.ts"
  "app/sitemap.ts"
  "app/error.tsx"
  "app/not-found.tsx"
  "app/admin/page.tsx"
  "app/admin/layout.tsx"
  "app/admin/FinanceTab.tsx"
  "app/admin/GiftCardsTab.tsx"
  "app/admin/InventoryTab.tsx"
  "app/admin/LiteModeView.tsx"
  "app/admin/PayrollTab.tsx"
  "app/admin/PromoCodesTab.tsx"
  "app/admin/ScheduleTab.tsx"
  "app/admin/ServicesTab.tsx"
  "app/admin/TimeClockTab.tsx"
  "app/admin/VibeTab.tsx"
  "app/api/admin/inventory-reminder/route.ts"
  "app/api/admin/users/route.ts"
  "app/api/analytics/route.ts"
  "app/api/analytics/track/route.ts"
  "app/api/auth/google/route.ts"
  "app/api/auth/login/route.ts"
  "app/api/auth/logout/route.ts"
  "app/api/auth/me/route.ts"
  "app/api/auth/signup/route.ts"
  "app/api/auth/totp-setup/route.ts"
  "app/api/auth/verify-totp/route.ts"
  "app/api/bookings/route.ts"
  "app/api/contact/route.ts"
  "app/api/email/route.ts"
  "app/api/finance/route.ts"
  "app/api/gift-card/route.ts"
  "app/api/inventory/route.ts"
  "app/api/marketing/automation/route.ts"
  "app/api/newsletter/route.ts"
  "app/api/packages/route.ts"
  "app/api/pay/route.ts"
  "app/api/promo-codes/route.ts"
  "app/api/qr/[customerId]/route.ts"
  "app/api/rewards/route.ts"
  "app/api/scan/route.ts"
  "app/api/schedule/route.ts"
  "app/api/schedule/blocks/route.ts"
  "app/api/serve-upload/route.ts"
  "app/api/services/route.ts"
  "app/api/services/seed/route.ts"
  "app/api/settings/route.ts"
  "app/api/staff/route.ts"
  "app/api/staff/portal/route.ts"
  "app/api/stripe/charge-noshow/route.ts"
  "app/api/stripe/checkout/route.ts"
  "app/api/stripe/save-card/route.ts"
  "app/api/stripe/setup-intent/route.ts"
  "app/api/stripe/webhook/route.ts"
  "app/api/timeclock/route.ts"
  "app/api/upload/route.ts"
  "app/about/page.tsx"
  "app/blog/page.tsx"
  "app/blog/best-balayage-upper-east-side/page.tsx"
  "app/blog/blowout-vs-keratin-treatment/page.tsx"
  "app/blog/your-first-visit-guide/page.tsx"
  "app/book/page.tsx"
  "app/book/layout.tsx"
  "app/contact/page.tsx"
  "app/contact/layout.tsx"
  "app/gallery/page.tsx"
  "app/gallery/layout.tsx"
  "app/gift-card/page.tsx"
  "app/gift-card/success/page.tsx"
  "app/login/page.tsx"
  "app/makeup/page.tsx"
  "app/packages/page.tsx"
  "app/packages/layout.tsx"
  "app/pay/[bookingId]/page.tsx"
  "app/pay/[bookingId]/PayClient.tsx"
  "app/rewards/page.tsx"
  "app/scan/page.tsx"
  "app/scan/[customerId]/page.tsx"
  "app/services/page.tsx"
  "app/services/layout.tsx"
  "app/signup/page.tsx"
  "app/staff/page.tsx"
  "app/staff/layout.tsx"
  "app/account/page.tsx"
  "app/account/layout.tsx"
  "app/account/appointments/page.tsx"
  "app/account/packages/page.tsx"
  "app/account/rewards/page.tsx"
  "app/team/page.tsx"
  "app/terms/page.tsx"
  "app/visit/page.tsx"
  "app/weddings/page.tsx"
  "components/AnalyticsTracker.tsx"
  "components/CurlyBot.tsx"
  "components/FadeIn.tsx"
  "components/FaqSection.tsx"
  "components/Footer.tsx"
  "components/GoogleSignInButton.tsx"
  "components/HeroLogo.tsx"
  "components/JsonLd.tsx"
  "components/MarqueeStrip.tsx"
  "components/MobileBookBar.tsx"
  "components/Navbar.tsx"
  "components/NewsletterStrip.tsx"
  "components/PromoPopup.tsx"
  "components/PublicShell.tsx"
  "components/ResultsGallery.tsx"
  "components/SectionDivider.tsx"
  "components/SplashScreen.tsx"
  "components/TeamStrip.tsx"
  "components/TestimonialsCarousel.tsx"
  "components/WorkShowcase.tsx"
  "lib/admin-totp.ts"
  "lib/admins.ts"
  "lib/analytics.ts"
  "lib/auth.ts"
  "lib/bookings.ts"
  "lib/customers.ts"
  "lib/data.ts"
  "lib/db.ts"
  "lib/email.ts"
  "lib/gift-cards.ts"
  "lib/inventory.ts"
  "lib/messages.ts"
  "lib/newsletter.ts"
  "lib/rate-limit.ts"
  "lib/schema.ts"
  "lib/stripe.ts"
  "lib/theme.ts"
  "lib/timeclock.ts"
  "lib/totp.ts"
  "lib/webhook-events.ts"
  "scripts/clear-bookings.js"
  "scripts/create-staff-accounts.js"
  "scripts/import-data.js"
  "scripts/seed-admin.js"
  "scripts/sync-from-github.sh"
  "types/replit-object-storage.d.ts"
)

echo "Syncing from GitHub: ${REPO}@${BRANCH}"
echo ""

SUCCESS=0
FAILED=0

for FILE in "${FILES[@]}"; do
  DIR=$(dirname "$FILE")
  mkdir -p "$DIR"
  URL="${BASE}/${FILE}"
  HTTP_CODE=$(curl -s -o "$FILE" -w "%{http_code}" "$URL")
  if [ "$HTTP_CODE" = "200" ]; then
    echo "  ✓ $FILE"
    SUCCESS=$((SUCCESS + 1))
  else
    echo "  ✗ $FILE (HTTP $HTTP_CODE)"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "Done: ${SUCCESS} updated, ${FAILED} failed."
echo ""
echo "Replit-only files preserved (not touched):"
for F in "${REPLIT_ONLY[@]}"; do
  echo "  • $F"
done
echo ""
echo "Next: redeploy the app to apply changes."
